version: '3.7'

services:

  test_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    volumes:
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data
    ports:
      - ${TEST_POSTGRES_PORT}:5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/postgresql/pg1-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
